### ISSUE TITLE
Prueba No. 12 - Menú

### ISSUE THREAD

**Issue by ingedwindiaz** [eduardo-thrash/LogisticApp#86]
Al dar clic las siguientes ventanas no abren: 
Delegado > Ver Resumen Sitio
Delegado > Ayuda
Delegado > Cabiar Contraseña (Esta opción no aparece en este rol)

**Comment by eduardo-thrash** [comment]
Se revisa el ajuste de Leidi desde codigo y es correcto. validar funcionalimente.
