### ISSUE TITLE
Prueba No. 2 - Login - Nombre de las cajas de texto

### ISSUE THREAD

**Issue by ingedwindiaz** [eduardo-thrash/LogisticApp#87]
El campo usuario y el de contraseña dicen "Número de Identificación", deberían decir Usuario y Contraseña, confunde un poco, el usuario podría digitar dos veces el número de identificación dado que eso dicen las cajas de texto

**Comment by eduardo-thrash** [comment]
Solucionado en PR https://github.com/eduardo-thrash/LogisticApp/pull/109
