### ISSUE TITLE
Pueba No. 10 - Menú - Menús de cada rol diferentes

### ISSUE THREAD

**Issue by ingedwindiaz** [eduardo-thrash/LogisticApp#88]
El Rol 1 y Rol 3 tienen una interfaz de Menú (Estilo) versión 1, diferente a las del Rol 2 y Rol 4, versión 2, la versión más moderna, se deberían unificar los estilos

**Comment by eduardo-thrash** [comment]
Solucionado en PR https://github.com/eduardo-thrash/LogisticApp/pull/103
